In [1]:
import pandas as pd


columns = ['Overall Qual', 'Overall Cond', 'Gr Liv Area',
           'Central Air', 'Total Bsmt SF', 'SalePrice']

df = pd.read_csv('http://jse.amstat.org/v19n3/decock/AmesHousing.txt', 
                 sep='\t',
                 usecols=columns)
del df['Central Air']




df.head()

Overall Qual  Overall Cond  Total Bsmt SF  Gr Liv Area  SalePrice
0             6             5         1080.0         1656     215000
1             5             6          882.0          896     105000
2             6             6         1329.0         1329     172000
3             7             5         2110.0         2110     244000
4             5             5          928.0         1629     189900

In [2]:
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
import numpy as np

from sklearn.metrics import r2_score

In [3]:
target = 'SalePrice'
features = df.columns[df.columns != target]
print(features)

X = df[features].values
print(X)
y = df[target].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=123)

Index(['Overall Qual', 'Overall Cond', 'Total Bsmt SF', 'Gr Liv Area'], dtype='object')
[[   6.    5. 1080. 1656.]
 [   5.    6.  882.  896.]
 [   6.    6. 1329. 1329.]
 ...
 [   5.    5.  912.  970.]
 [   5.    5. 1389. 1389.]
 [   7.    5.  996. 2000.]]


In [4]:
forest = RandomForestRegressor(n_estimators=1000,criterion='squared_error',random_state=1,n_jobs=-1)
print('  :::')
print(X_train)
print(X_test)

forest.fit(X_train, y_train)
y_train_pred = forest.predict(X_train)
y_test_pred = forest.predict(X_test)

mae_train = mean_absolute_error(y_train,y_train_pred)
mae_test = mean_absolute_error(y_test,y_test_pred)

print(f'MAE Train: {mae_train:.2f}')
print(f'MAE Test: {mae_test:.2f}')

r2_train = r2_score(y_train,y_train_pred)
r2_test = r2_score(y_test,y_test_pred)

print(f'R^2 Train: {r2_train:.2f}')
print(f'R^2 Test: {r2_test:.2f}')


  :::
[[   3.    5.    0. 2034.]
 [   5.    7.  876.  904.]
 [   6.    5.  547. 1072.]
 ...
 [   7.    5. 1066. 2385.]
 [   7.    5. 1428. 1428.]
 [   5.    5. 1100. 1902.]]
[[   5.    7.  660. 1656.]
 [   4.    5. 1005. 1005.]
 [   6.    5. 1040. 1097.]
 ...
 [   5.    6. 1598. 3086.]
 [   5.    5.  864.  892.]
 [   7.    5. 1306. 2260.]]


ValueError: Input contains NaN, infinity or a value too large for dtype('float32').